plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.quickfilter.remote'
    compileSdk 34

    defaultConfig {
        applicationId "com.quickfilter.remote"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("keystore/qf-release.keystore")
            storePassword "qf-remote-2026"
            keyAlias "qf"
            keyPassword "qf-remote-2026"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'io.coil-kt:coil:2.6.0'
}
